// frontend/v1.1/app/components/NotificationBell.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router";
import { notificationApi, type Notification } from "../utils/api";

const kindText = (n: Notification): string => {
  const actor = n.actorName || `user #${n.actorId}`;
  switch (n.kind) {
    case "follow":
      return `${actor} followed you`;
    case "comment":
      return `${actor} commented on your post`;
    case "reaction":
      return `${actor} reacted to your post`;
    default:
      return `${actor} did something`;
  }
};

/**
 * Navbar bell with an unread badge and a dropdown of recent notifications.
 * Polls the unread count once a minute while logged in.
 */
export function NotificationBell() {
  const [unread, setUnread] = useState(0);
  const [items, setItems] = useState<Notification[]>([]);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);

  const refreshCount = async () => {
    try {
      const res = await notificationApi.unreadCount();
      if (res.code === 200) setUnread(res.body?.data ?? 0);
    } catch {
      // Not logged in or backend unreachable; keep the badge quiet.
    }
  };

  useEffect(() => {
    refreshCount();
    const timer = setInterval(refreshCount, 60_000);
    return () => clearInterval(timer);
  }, []);

  const toggleOpen = async () => {
    const next = !open;
    setOpen(next);
    if (next) {
      setLoading(true);
      try {
        const res = await notificationApi.list({ limit: 10 });
        if (res.code === 200 && res.body?.data) setItems(res.body.data);
      } catch {
        setItems([]);
      } finally {
        setLoading(false);
      }
    }
  };

  const markAllRead = async () => {
    try {
      await notificationApi.markAllRead();
      setUnread(0);
      setItems((prev) => prev.map((n) => ({ ...n, isRead: true })));
    } catch (e) {
      console.error("Failed to mark notifications read", e);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={toggleOpen}
        className="btn btn-ghost btn-xs relative"
        aria-label="Notifications"
      >
        🔔
        {unread > 0 && (
          <span className="badge badge-error badge-xs absolute -top-1 -right-1 font-mono">
            {unread > 99 ? "99+" : unread}
          </span>
        )}
      </button>
      {open && (
        <div className="absolute right-0 mt-2 w-72 z-50 card card-border bg-base-100 shadow-lg p-2 text-left">
          <div className="flex items-center justify-between px-2 py-1 border-b border-base-300">
            <span className="text-xs font-bold uppercase tracking-wide">Notifications</span>
            {unread > 0 && (
              <button className="btn btn-ghost btn-xs text-primary" onClick={markAllRead}>
                Mark all read
              </button>
            )}
          </div>
          {loading ? (
            <div className="p-3 text-center">
              <span className="loading loading-spinner loading-xs"></span>
            </div>
          ) : items.length === 0 ? (
            <div className="p-3 text-xs text-center opacity-60">No notifications yet.</div>
          ) : (
            <ul className="max-h-72 overflow-y-auto">
              {items.map((n) => (
                <li
                  key={n.id}
                  className={`px-2 py-1.5 text-xs border-b border-base-200 last:border-0 ${
                    n.isRead ? "opacity-60" : "font-semibold"
                  }`}
                >
                  {n.postId ? (
                    <Link to={`/posts/${n.postId}`} onClick={() => setOpen(false)} className="hover:text-primary">
                      {kindText(n)}
                    </Link>
                  ) : (
                    <Link to={`/profile/${n.actorId}`} onClick={() => setOpen(false)} className="hover:text-primary">
                      {kindText(n)}
                    </Link>
                  )}
                  <div className="text-[10px] opacity-50 font-mono">
                    {new Date(n.createdAt).toLocaleString()}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

// frontend/src/components/NotificationBell.vue
<script setup lang="ts">
import { Bell, CheckCheck, LoaderCircle } from "lucide-vue-next";
import { onBeforeUnmount, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { notificationApi } from "../api";
import { timeAgo } from "../lib/format";
import { describe } from "../lib/notifications";
import type { Notification } from "../types";

const router = useRouter();
const unread = ref(0);
const items = ref<Notification[]>([]);
const loading = ref(false);
let timer = 0;

const refresh = async () => {
  const response = await notificationApi.unread();
  unread.value = response.body?.data || 0;
};

const load = async () => {
  loading.value = true;
  try {
    const response = await notificationApi.list({ limit: 6 });
    items.value = response.body?.data || [];
  } finally {
    loading.value = false;
  }
};

/** daisyUI dropdowns stay open while focused; blur closes them. */
const close = () => (document.activeElement as HTMLElement | null)?.blur();

const open = async (item: Notification) => {
  if (!item.isRead) {
    await notificationApi.read(item.id).catch(() => undefined);
    item.isRead = true;
    unread.value = Math.max(0, unread.value - 1);
  }
  close();
  router.push(item.postId ? `/posts/${item.postId}` : `/profile/${item.actorId}`);
};

const readAll = async () => {
  await notificationApi.readAll();
  unread.value = 0;
  items.value = items.value.map(item => ({ ...item, isRead: true }));
};

onMounted(() => {
  refresh().catch(() => undefined);
  timer = window.setInterval(() => refresh().catch(() => undefined), 60_000);
});
onBeforeUnmount(() => window.clearInterval(timer));
</script>

<template>
  <div class="dropdown dropdown-end">
    <button tabindex="0" class="btn btn-ghost btn-circle" aria-label="Notifications" @click="load">
      <div class="indicator"><Bell :size="19" /><span v-if="unread" class="badge badge-error badge-xs indicator-item">{{ unread > 99 ? "99+" : unread }}</span></div>
    </button>
    <div tabindex="0" class="dropdown-content card card-border z-50 mt-3 w-80 bg-base-100 shadow-2xl">
      <div class="card-body gap-2 p-3">
        <div class="flex items-center justify-between px-1"><h3 class="font-bold">Notifications</h3><button class="btn btn-ghost btn-xs" :disabled="!unread" @click="readAll"><CheckCheck :size="15" /> Read all</button></div>
        <div v-if="loading" class="grid place-items-center py-8"><LoaderCircle class="animate-spin" /></div>
        <template v-else>
          <button v-for="item in items" :key="item.id" class="rounded-box p-3 text-left transition hover:bg-base-200" :class="{ 'bg-primary/8': !item.isRead }" @click="open(item)">
            <span class="text-sm"><strong>{{ item.actorName || `User ${item.actorId}` }}</strong> {{ describe(item) }}</span>
            <small class="mt-1 block text-base-content/50">{{ timeAgo(item.createdAt) }}</small>
          </button>
          <p v-if="!items.length" class="py-8 text-center text-sm text-base-content/55">You're all caught up.</p>
        </template>
        <RouterLink to="/notifications" class="btn btn-ghost btn-sm" @click="close">View all</RouterLink>
      </div>
    </div>
  </div>
</template>
